# Copybooks MUST be listed as prerequisites. TOBi only rebuilds when a named
# prerequisite is newer, so a module that lists just its own source will not
# rebuild when a copybook it includes changes - and the build reports
# "Nothing to be done" rather than anything being wrong. The service program
# then keeps the old record layouts while a freshly compiled caller uses the
# new ones, and fields are read at the wrong offsets.
#
# TRANSITIVE INCLUDES COUNT. A copybook that includes another puts BOTH in the
# module's dependency set, and it is the indirect one that gets forgotten -
# SCMAIN reaches SCQRY_D only through SCEXEC_D, and did not list it until a
# type from SCQRY_D started crossing that boundary. Eight rules were
# under-declared when this was last swept on 8 September 2026; the sweep is
# worth repeating whenever a copybook gains an include.
SCYAML.MODULE: SCYAML.RPGLE QPROTOSRC/SCYAML_D.RPGLEINC
SCYAML.MODULE: TEXT = RMSC: YAML reader

SCDEF.MODULE: SCDEF.RPGLE QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCYAML_D.RPGLEINC
SCDEF.MODULE: TEXT = RMSC: Service definition model

SCDIRS.MODULE: SCDIRS.SQLRPGLE QPROTOSRC/SCDIRS_D.RPGLEINC
SCDIRS.MODULE: TEXT = RMSC: Definition directory resolution

SCCOLL.MODULE: SCCOLL.RPGLE QPROTOSRC/SCCOLL_D.RPGLEINC QPROTOSRC/SCDEF_D.RPGLEINC \
               QPROTOSRC/SCDIRS_D.RPGLEINC QPROTOSRC/SCOUT_D.RPGLEINC \
               QPROTOSRC/SCYAML_D.RPGLEINC
SCCOLL.MODULE: TEXT = RMSC: Service definition collection

SCNET.MODULE: SCNET.RPGLE QPROTOSRC/SCNET_D.RPGLEINC QPROTOSRC/SCYAML_D.RPGLEINC
SCNET.MODULE: TEXT = RMSC: Network status via QtocLstNetCnn

SCJOB.MODULE: SCJOB.RPGLE QPROTOSRC/SCJOB_D.RPGLEINC QPROTOSRC/SCQRY_D.RPGLEINC \
              QPROTOSRC/SCYAML_D.RPGLEINC
SCJOB.MODULE: TEXT = RMSC: Active job lookup via QUSLJOB

SCQRY.MODULE: SCQRY.SQLRPGLE QPROTOSRC/SCQRY_D.RPGLEINC QPROTOSRC/SCNET_D.RPGLEINC \
              QPROTOSRC/SCJOB_D.RPGLEINC QPROTOSRC/SCYAML_D.RPGLEINC
SCQRY.MODULE: TEXT = RMSC: System queries

SCOUT.MODULE: SCOUT.RPGLE QPROTOSRC/SCOUT_D.RPGLEINC
SCOUT.MODULE: TEXT = RMSC: Output formatting

SCLAUNCH.MODULE: SCLAUNCH.RPGLE QPROTOSRC/SCLAUNCH_D.RPGLEINC \
                 QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCQRY_D.RPGLEINC \
                 QPROTOSRC/SCYAML_D.RPGLEINC
SCLAUNCH.MODULE: TEXT = RMSC: Service launch

SCLOG.MODULE: SCLOG.RPGLE QPROTOSRC/SCLOG_D.RPGLEINC QPROTOSRC/SCDEF_D.RPGLEINC \
              QPROTOSRC/SCDIRS_D.RPGLEINC QPROTOSRC/SCYAML_D.RPGLEINC
SCLOG.MODULE: TEXT = RMSC: Service log location

SCEXEC.MODULE: SCEXEC.RPGLE QPROTOSRC/SCEXEC_D.RPGLEINC QPROTOSRC/SCCOLL_D.RPGLEINC \
               QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCLAUNCH_D.RPGLEINC \
               QPROTOSRC/SCLOG_D.RPGLEINC QPROTOSRC/SCOUT_D.RPGLEINC \
               QPROTOSRC/SCQRY_D.RPGLEINC QPROTOSRC/SCYAML_D.RPGLEINC
SCEXEC.MODULE: TEXT = RMSC: Service operations

SCMAIN.MODULE: SCMAIN.RPGLE QPROTOSRC/SCMAIN_D.RPGLEINC QPROTOSRC/SCCOLL_D.RPGLEINC \
               QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCEXEC_D.RPGLEINC \
               QPROTOSRC/SCOUT_D.RPGLEINC QPROTOSRC/SCQRY_D.RPGLEINC \
               QPROTOSRC/SCYAML_D.RPGLEINC
SCMAIN.MODULE: TEXT = RMSC: Command line

SCRUN.PGM: SCRUN.PGM.RPGLE QPROTOSRC/SCMAIN_D.RPGLEINC QPROTOSRC/SCDEF_D.RPGLEINC \
           QPROTOSRC/SCOUT_D.RPGLEINC QPROTOSRC/SCQRY_D.RPGLEINC \
           QPROTOSRC/SCYAML_D.RPGLEINC RMSCPGM.BNDDIR
SCRUN.PGM: TEXT = RMSC: Service Commander

SCCMD.PGM: SCCMD.PGM.RPGLE QPROTOSRC/SCMAIN_D.RPGLEINC QPROTOSRC/SCDEF_D.RPGLEINC \
           QPROTOSRC/SCOUT_D.RPGLEINC QPROTOSRC/SCQRY_D.RPGLEINC \
           QPROTOSRC/SCYAML_D.RPGLEINC RMSCPGM.BNDDIR
SCCMD.PGM: TEXT = RMSC: SC command processing program

SCAPI.MODULE: SCAPI.RPGLE QPROTOSRC/SCAPI_D.RPGLEINC QPROTOSRC/SCCOLL_D.RPGLEINC \
              QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCEXEC_D.RPGLEINC \
              QPROTOSRC/SCOUT_D.RPGLEINC QPROTOSRC/SCQRY_D.RPGLEINC \
              QPROTOSRC/SCYAML_D.RPGLEINC
SCAPI.MODULE: TEXT = RMSC: Bound-call API





