# Copybooks MUST be listed as prerequisites. TOBi only rebuilds when a named
# prerequisite is newer, so a module that lists just its own source will not
# rebuild when a copybook it includes changes - and the build reports
# "Nothing to be done" rather than anything being wrong. The service program
# then keeps the old record layouts while a freshly compiled caller uses the
# new ones, and fields are read at the wrong offsets.
SCYAML.MODULE: SCYAML.RPGLE QPROTOSRC/SCYAML_D.RPGLEINC
SCYAML.MODULE: TEXT = RMSC: YAML reader

SCDEF.MODULE: SCDEF.RPGLE QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCYAML_D.RPGLEINC
SCDEF.MODULE: TEXT = RMSC: Service definition model

SCDIRS.MODULE: SCDIRS.SQLRPGLE QPROTOSRC/SCDIRS_D.RPGLEINC
SCDIRS.MODULE: TEXT = RMSC: Definition directory resolution

SCCOLL.MODULE: SCCOLL.RPGLE QPROTOSRC/SCCOLL_D.RPGLEINC QPROTOSRC/SCDEF_D.RPGLEINC \
               QPROTOSRC/SCDIRS_D.RPGLEINC QPROTOSRC/SCYAML_D.RPGLEINC
SCCOLL.MODULE: TEXT = RMSC: Service definition collection

SCQRY.MODULE: SCQRY.SQLRPGLE QPROTOSRC/SCQRY_D.RPGLEINC
SCQRY.MODULE: TEXT = RMSC: System queries

SCOUT.MODULE: SCOUT.RPGLE QPROTOSRC/SCOUT_D.RPGLEINC
SCOUT.MODULE: TEXT = RMSC: Output formatting

SCLAUNCH.MODULE: SCLAUNCH.RPGLE QPROTOSRC/SCLAUNCH_D.RPGLEINC \
                 QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCQRY_D.RPGLEINC
SCLAUNCH.MODULE: TEXT = RMSC: Service launch

SCLOG.MODULE: SCLOG.RPGLE QPROTOSRC/SCLOG_D.RPGLEINC QPROTOSRC/SCDEF_D.RPGLEINC \
              QPROTOSRC/SCDIRS_D.RPGLEINC
SCLOG.MODULE: TEXT = RMSC: Service log location

SCEXEC.MODULE: SCEXEC.RPGLE QPROTOSRC/SCEXEC_D.RPGLEINC QPROTOSRC/SCCOLL_D.RPGLEINC \
               QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCLAUNCH_D.RPGLEINC \
               QPROTOSRC/SCLOG_D.RPGLEINC QPROTOSRC/SCOUT_D.RPGLEINC \
               QPROTOSRC/SCQRY_D.RPGLEINC
SCEXEC.MODULE: TEXT = RMSC: Service operations

SCMAIN.MODULE: SCMAIN.RPGLE QPROTOSRC/SCMAIN_D.RPGLEINC QPROTOSRC/SCCOLL_D.RPGLEINC \
               QPROTOSRC/SCDEF_D.RPGLEINC QPROTOSRC/SCEXEC_D.RPGLEINC \
               QPROTOSRC/SCOUT_D.RPGLEINC
SCMAIN.MODULE: TEXT = RMSC: Command line

SCRUN.PGM: SCRUN.PGM.RPGLE QPROTOSRC/SCMAIN_D.RPGLEINC RMSCPGM.BNDDIR
SCRUN.PGM: TEXT = RMSC: Service Commander

SCCMD.PGM: SCCMD.PGM.RPGLE QPROTOSRC/SCMAIN_D.RPGLEINC RMSCPGM.BNDDIR
SCCMD.PGM: TEXT = RMSC: SC command processing program
